// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC80VASju7-i8HrT61Gk3XNfQZyS-apUOg',
    appId: '1:123865941776:web:e1ff55ed7e32b1d7da4795',
    messagingSenderId: '123865941776',
    projectId: 'b-11-9cd91',
    authDomain: 'b-11-9cd91.firebaseapp.com',
    storageBucket: 'b-11-9cd91.firebasestorage.app',
    measurementId: 'G-GJXZR4RKF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3R7MWjfW6gtG2si6hLhCwmxvPiwk187c',
    appId: '1:123865941776:android:488491706af2197bda4795',
    messagingSenderId: '123865941776',
    projectId: 'b-11-9cd91',
    storageBucket: 'b-11-9cd91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlyMEeb4foB5EFHR5bTs3s2Pcc-GZs2U',
    appId: '1:123865941776:ios:5fc2b0b9bfbb672cda4795',
    messagingSenderId: '123865941776',
    projectId: 'b-11-9cd91',
    storageBucket: 'b-11-9cd91.firebasestorage.app',
    iosBundleId: 'com.example.b11',
  );
}
